["Failer"]
schedule = "* * * * *"
image = "alpine"
command = "sleep 30"
network = "not_a_real_net"

["Pinger"]
schedule = "* * * * *"
image = "alpine"
command = "ping -c 30 87c2f9246231"
network = "test_net"
